# Generated by Django 4.1 on 2022-09-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_taskmodel_budget_taskmodel_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='isPending',
            field=models.BooleanField(default=False),
        ),
    ]
