# Generated by Django 4.1 on 2022-09-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_taskmodel_ispending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
