# Generated by Django 4.1 on 2022-09-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_alter_taskmodel_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='isCancelled',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='isComplete',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='isPending',
        ),
    ]
