# Generated by Django 4.1 on 2022-09-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_remove_taskmodel_iscancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Pending', 'Cancelled')], default='Complete', max_length=10),
        ),
    ]
