# Generated by Django 4.1 on 2022-09-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_projectmodel_taskmodel_taskproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='taskproject',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='projects',
            field=models.CharField(choices=[((('', ''), ('Webapp', 'Webapp')), ('AI', 'AI'))], default='Complete', max_length=10),
        ),
    ]
