# Generated by Django 4.1 on 2022-09-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_remove_taskmodel_taskproject_taskmodel_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='projects',
            field=models.CharField(choices=[('', ''), ('Webapp', 'Webapp'), ('AI', 'AI')], default='Complete', max_length=10),
        ),
    ]
