# Generated by Django 4.1 on 2022-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0011_alter_taskmodel_cost_alter_taskmodel_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
